version: "3.9"
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    volumes:
      - ./app/server:/app
      # exclude static files to preserve frontend changes
      - /app/static
    env_file:
      - .env.development
  db:
    image: "mysql:8.0"
    restart: "always"
    env_file:
      - .env.development
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/seed/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
